name: Mypy Type Check

on:
  push:
    branches: [githubactions]
  pull_request:
    branches: [githubactions]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Change to match your project's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install -r requirements.txt  # Optional, if you have other dependencies

      - name: Run mypy
        run: |
          mypy .  # Runs mypy on the current directory
